name:                danielmroz-co-uk
version:             0.1.0.0
github:              "zyxw121/danielmroz.co.uk"
license:             BSD3
author:              "Daniel Mroz"
maintainer:          ""
copyright:           "2019 Daniel Mroz"

extra-source-files:
- README.md
- ChangeLog.md


# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zyxw121/danielmroz.co.uk#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies: 
  - blaze-html
  - aeson

executables:
  website:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - danielmroz-co-uk
    - pandoc
    - skylighting
    - pandoc-types
    - text
    - blaze-html
    - directory
    - filepath
    - aeson
    - bytestring

  publish:
    main: Main.hs
    source-dirs: publish
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - danielmroz-co-uk
    - pandoc
    - skylighting
    - pandoc-types
    - text
    - blaze-html
    - directory
    - filepath
    - aeson
    - bytestring
    - aeson-pretty


tests:
  danielmroz-co-uk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - danielmroz-co-uk
